<?php
define('HTTP_CODE_SUCCESS', 200);
define('HTTP_CODE_BAD_REQUEST', 400);
define('HTTP_CODE_UNAUTHORIZED', 401);
define('HTTP_CODE_NOT_ACCEPTABLE', 406);
define('HTTP_CODE_CONFLICT', 409);
define('HTTP_CODE_SERVICE_UNAVAILABLE', 503);

define('STATUS_SUCCESS', 'SUCCESS');
define('STATUS_FAILED', 'FAILED');
define('STATUS_HOLD', 'HOLD');
define('STATUS_REFUND', 'REFUND');
define('STATUS_CANCEL', 'CANCEL');
define('STATUS_PROCESSING', 'PROCESSING');
define('STATUS_PENDING', 'PENDING');
define('STATUS_UNDEFINED', 'UNDEFINED');
define('STATUS_ERROR', 'ERROR');

define('RESULT_CODE_SUCCESS', 1001);
define('RESULT_CODE_HOLD', 1002);
define('RESULT_CODE_FAILED', 9999);
define('RESULT_CODE_TECHNICAL_ERROR', 2001);
define('RESULT_CODE_ERROR_WITH_SERVICE_PROVIDER', 2002);
define('RESULT_CODE_SERVICE_NOT_AVAILABLE', 2003);
define('RESULT_CODE_AUTHENTICATION_FAILED', 2004);
define('RESULT_CODE_SERVER_DOWN', 2005);
define('RESULT_CODE_CANNOT_PROCESS_THIS_REQUEST', 2006);
define('RESULT_CODE_ENCRYPTION_FAILED', 2007);
define('RESULT_CODE_DECRYPTION_FAILED', 2008);
define('RESULT_CODE_HASH_VALIDATION_FAILED', 2009);
define('RESULT_CODE_NO_ACTIVE_ACCOUNT_FOUND', 2011);
define('RESULT_CODE_ACCOUNT_NOT_FOUND_FOR_USER', 2012);
define('RESULT_CODE_DOB_MISMATCH', 2013);
define('RESULT_CODE_MOBILE_NUMBER_NOT_FOUND', 2014);
define('RESULT_CODE_INVALID_ACCOUNT', 2021);
define('RESULT_CODE_ACCOUNT_NUMBER_AND_MOBILE_NUMBER_DO_NOT_MATCH', 2022);
define('RESULT_CODE_INSUFFICIENT_ACCOUNT_BALANCE', 8899);
define('RESULT_CODE_ACCOUNT_NOT_FOUND', 8898);
define('RESULT_CODE_ACCOUNT_IS_INACTIVE_BLOCKED_CLOSED', 8897);
define('RESULT_CODE_DEBIT_IS_NOT_ALLOWED', 8896);
define('RESULT_CODE_CREDIT_IS_NOT_ALLOWED', 8895);
define('RESULT_CODE_USER_DECLINED', 8894);
define('RESULT_CODE_TIME_EXPIRED', 8893);
define('RESULT_CODE_ATTEMPTS_TO_RETRY_EXCEEDED_MAXIMUM', 8892);
define('RESULT_CODE_SETTLEMENT_ACCOUNT_NOT_FOUND', 8891);
define('RESULT_CODE_ENTITY_IS_INACTIVE', 9988);
define('RESULT_CODE_INSUFFICIENT_VIRTUAL_ACCOUNT_BALANCE', 9989);
define('RESULT_CODE_TRANSACTION_DETAILS_DO_NOT_MATCH', 2091);
define('RESULT_CODE_TRANSACTION_REFERENCE_IS_NOT_UNIQUE', 2092);
define('RESULT_CODE_TRANSACTION_REFERENCE_MUST_BE_SAME', 2093);

define('RESULT_MESSAGE_E1001', 'The request is successfully processed');
define('RESULT_MESSAGE_E1002', 'The status updated as hold');
define('RESULT_MESSAGE_E9999', 'Processed request failed');
define('RESULT_MESSAGE_E2001', 'Failed due to technical error');
define('RESULT_MESSAGE_E2002', 'Error with Service Provider');
define('RESULT_MESSAGE_E2003', 'Service not available');
define('RESULT_MESSAGE_E2004', 'Authentication Failed');
define('RESULT_MESSAGE_E2005', 'Server Down');
define('RESULT_MESSAGE_E2006', 'Cannot process this request');
define('RESULT_MESSAGE_E2007', 'Encryption failed');
define('RESULT_MESSAGE_E2008', 'Decryption failed');
define('RESULT_MESSAGE_E2009', 'Hash validation failed');
define('RESULT_MESSAGE_E2011', 'No active account found');
define('RESULT_MESSAGE_E2012', 'Account not found for user');
define('RESULT_MESSAGE_E2013', 'DOB mismatch');
define('RESULT_MESSAGE_E2014', 'Mobile number not found');
define('RESULT_MESSAGE_E2021', 'Invalid account');
define('RESULT_MESSAGE_E2022', 'Account number and mobile number do not match');
define('RESULT_MESSAGE_E2091', 'Transaction details do not match');
define('RESULT_MESSAGE_E2092', 'Transaction reference is not unique');
define('RESULT_MESSAGE_E2093', 'The transaction reference must be the same as the HOLD');
define('RESULT_MESSAGE_E8899', 'Insufficient account balance');
define('RESULT_MESSAGE_E8898', 'Account not found');
define('RESULT_MESSAGE_E8897', 'Account is inactive / blocked / closed');
define('RESULT_MESSAGE_E8896', 'Debit is not allowed');
define('RESULT_MESSAGE_E8895', 'Credit is not allowed');
define('RESULT_MESSAGE_E8894', 'User declined');
define('RESULT_MESSAGE_E8893', 'Time expired');
define('RESULT_MESSAGE_E8892', 'Attempts to retry exceeded maximum');
define('RESULT_MESSAGE_E8891', 'Settlement account not found');
define('RESULT_MESSAGE_E9988', 'Entity is inactive');
define('RESULT_MESSAGE_E9989', 'Insufficient virtual account balance');
?>